module.exports={
    server:{
        "port":3004
    },
    db:{
        'uri':"mongodb+srv://rutvik:17bit008@productcatalog.poqge.mongodb.net/ProductCatalog?retryWrites=true&w=majority",
        'uriTest':"mongodb://localhost/bags-ecommerce"
    },
    kafka:{
        "hostName":"localhost:9092",
        "topics":{
            "inventory":"InventoryStream",
            "order":"OrderStream",
            "payment":"paymentStream"
        }
    }
}